### ISSUE TITLE
Unhandled situation when the API returns inconsistent results

### ISSUE THREAD

**Issue by bradwbonn** [bradwbonn/bradtestrepo#1]
The API for monitoring usually behaves consistently, but there are times that the data points are not in the same place, or have missing data.  cluster_disk.py script will need to handle those situations. 
Right now, it can sometimes exit with:

```
Traceback (most recent call last):
File "./cluster_disk.py", line 135, in <module>
main(sys.argv[1:])
File "./cluster_disk.py", line 35, in main
get_disk_state_of_node(node, account, cluster)
File "./cluster_disk.py", line 81, in get_disk_state_of_node
current_bytes_free = float(disk_free['target_responses'][0]['datapoints'][curr_free_key][0])
```

**Comment by bradwbonn** [comment]
Fixed in today's update.
